// Anti-aliased bitmap font format, generated by tools/fontgen/fontgen.py
#pragma once
#include <stdint.h>

struct Glyph
{
    uint16_t code;   // Unicode code point
    uint8_t w, h;    // bitmap size
    int8_t dx, dy;   // top-left of the bitmap relative to the pen position on the baseline
    uint8_t advance; // horizontal pen advance
    uint32_t offset; // start of the 4 bit alpha data in Font::bitmap
};

struct Font
{
    const uint8_t *bitmap;
    const Glyph *glyphs; // sorted by code point
    uint16_t glyphCount;
    uint8_t ascent;
    uint8_t lineHeight;
};
