#!/usr/bin/env python3
"""Rasterize a TrueType/OpenType font into a C header for lib/ui (anti-aliased, 4 bit alpha).

The generated headers are committed, so building the firmware does not need this script.
Only run it to change fonts or sizes (see generate_fonts.sh). Requires Pillow.

Glyph data layout (see lib/ui/Font.h):
  - one Glyph entry per code point, sorted by code point (binary search at runtime)
  - bitmap: per glyph w*h alpha values, 4 bit each, high nibble first, row-major,
    every glyph starts on a byte boundary
  - dx/dy: offset of the bitmap's top-left corner relative to the pen position on the baseline
"""
import argparse
import pathlib

from PIL import Image, ImageDraw, ImageFont


def rasterize(font, ch):
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    advance = round(font.getlength(ch))
    if x1 <= x0 or y1 <= y0:
        return {"w": 0, "h": 0, "dx": 0, "dy": 0, "adv": advance, "alpha": []}
    w, h = x1 - x0, y1 - y0
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
    alpha = [(v * 15 + 127) // 255 for v in img.tobytes()]
    return {"w": w, "h": h, "dx": x0, "dy": y0, "adv": advance, "alpha": alpha}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--size", type=int, required=True, help="font size in pixels")
    ap.add_argument("--name", required=True, help="C identifier, e.g. font_body")
    ap.add_argument("--chars", required=True, help="characters to include")
    ap.add_argument("--tabular-digits", action="store_true", help="give all digits the same advance")
    ap.add_argument("--license", default="", help="license note for the header comment")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    font = ImageFont.truetype(args.ttf, args.size)
    ascent, descent = font.getmetrics()
    chars = sorted(set(args.chars), key=ord)
    glyphs = {ch: rasterize(font, ch) for ch in chars}

    if args.tabular_digits:
        digit_adv = max(glyphs[d]["adv"] for d in "0123456789" if d in glyphs)
        for d in "0123456789":
            if d in glyphs:
                g = glyphs[d]
                g["dx"] += (digit_adv - g["adv"]) // 2
                g["adv"] = digit_adv

    bitmap = bytearray()
    entries = []
    for ch in chars:
        g = glyphs[ch]
        for k in ("dx", "dy"):
            assert -128 <= g[k] <= 127, (ch, k, g[k])
        assert g["w"] < 256 and g["h"] < 256 and g["adv"] < 256, ch
        offset = len(bitmap)
        a = g["alpha"] + ([0] if len(g["alpha"]) % 2 else [])
        bitmap += bytes((a[i] << 4) | a[i + 1] for i in range(0, len(a), 2))
        entries.append(f"    {{0x{ord(ch):04x}, {g['w']}, {g['h']}, {g['dx']}, {g['dy']}, {g['adv']}, {offset}}}, // {ch!r}")

    n = args.name
    hex_lines = [", ".join(f"0x{b:02x}" for b in bitmap[i:i + 20]) for i in range(0, len(bitmap), 20)]
    src = pathlib.Path(args.ttf).name
    out = f"""// Generated by tools/fontgen/fontgen.py - do not edit
// Source: {src}, {args.size} px{', ' + args.license if args.license else ''}
#pragma once
#include "../Font.h"

static const uint8_t {n}_bitmap[] = {{
    {(',' + chr(10) + '    ').join(hex_lines)}
}};

static const Glyph {n}_glyphs[] = {{
{chr(10).join(entries)}
}};

static const Font {n} = {{{n}_bitmap, {n}_glyphs, {len(entries)}, {ascent}, {ascent + descent}}};
"""
    pathlib.Path(args.out).write_text(out, encoding="utf-8")
    print(f"{n}: {len(entries)} glyphs, {len(bitmap)} bytes bitmap, ascent {ascent}, line {ascent + descent}")


if __name__ == "__main__":
    main()
