"""Writes include/generated/build_info.h with the git commit of the build.

Runs automatically as a PlatformIO pre-build script; can also be run standalone:
python scripts/build_info.py. Without git (e.g. a source archive) the commit is "unknown".
"""
import pathlib
import subprocess

try:
    Import("env")  # noqa: F821 - provided by PlatformIO/SCons
    ROOT = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
except NameError:
    ROOT = pathlib.Path(__file__).resolve().parent.parent

OUT = ROOT / "include" / "generated" / "build_info.h"


def git(*args):
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()


def main():
    try:
        commit = git("rev-parse", "--short=7", "HEAD")
        # uncommitted changes in tracked files (generated files are ignored by git)
        dirty = git("status", "--porcelain", "--untracked-files=no") != ""
    except (OSError, subprocess.CalledProcessError):
        commit, dirty = "unknown", False
    header = (
        "// Generated by scripts/build_info.py - do not edit\n"
        "#pragma once\n\n"
        f'#define BUILD_COMMIT "{commit}"\n'
        f"#define BUILD_DIRTY {'true' if dirty else 'false'}\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    # Only touch the file when the content changed, to avoid needless rebuilds
    if not OUT.exists() or OUT.read_text() != header:
        OUT.write_text(header)
        print(f"build_info: commit {commit}{' (dirty)' if dirty else ''}")


main()
