"""Embed the web UI into the firmware.

Compresses web/index.html with gzip and writes include/generated/web_index_html.h,
which main.cpp serves with "Content-Encoding: gzip". Runs automatically as a
PlatformIO pre-build script; can also be run standalone: python scripts/embed_web.py
"""
import gzip
import pathlib

try:
    Import("env")  # noqa: F821 - provided by PlatformIO/SCons
    ROOT = pathlib.Path(env.subst("$PROJECT_DIR"))  # noqa: F821
except NameError:
    ROOT = pathlib.Path(__file__).resolve().parent.parent

SRC = ROOT / "web" / "index.html"
OUT = ROOT / "include" / "generated" / "web_index_html.h"


def main():
    data = gzip.compress(SRC.read_bytes(), compresslevel=9, mtime=0)
    lines = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    header = (
        "// Generated by scripts/embed_web.py from web/index.html - do not edit\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        "#include <stddef.h>\n\n"
        f"const size_t WEB_INDEX_HTML_GZ_LEN = {len(data)};\n"
        "const uint8_t WEB_INDEX_HTML_GZ[] = {\n    " + ",\n    ".join(lines) + "\n};\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    # Only touch the file when the content changed, to avoid needless rebuilds
    if not OUT.exists() or OUT.read_text() != header:
        OUT.write_text(header)
        print(f"embed_web: {SRC.name} -> {OUT.relative_to(ROOT)} ({SRC.stat().st_size} -> {len(data)} bytes gzip)")


main()
